/**
 * Autor: Brandon Medina
 * Fecha: 18/05/2026
 * Descripcion: Datos oficiales NENEZ para eventos, artistas y merch premium.
 */

import type { Artist, Event, MerchItem } from "@/frontend/types/domain";

export const artists: Artist[] = [
  {
    id: "yan-block",
    name: "YAN BLOCK",
    role: "TRAP LOUD EXPERIENCE",
    image: "/images/yan_block_artist_1779161408288.png",
    socials: { instagram: "https://instagram.com/yanblock" },
    description: "La nueva cara del trap latino oscuro. Letras crudas y flows inigualables.",
  },
  {
    id: "omar-courtz",
    name: "OMAR COURTZ",
    role: "LATIN LOUD",
    image: "/images/omar_courtz_artist_1779161689015.png",
    socials: { instagram: "https://instagram.com/omarcourtz" },
    description: "Voz unica y flows de la calle. Autenticidad reggaetonera premium.",
  },
  {
    id: "roa",
    name: "ROA",
    role: "TRAP LOUD",
    image: "/images/roa_artist_1779161704881.png",
    socials: { instagram: "https://instagram.com/roa" },
    description: "El futuro de la escena urbana. Versatilidad y melodias adictivas.",
  },
  {
    id: "anuel-aa",
    name: "ANUEL AA",
    role: "HEADLINER",
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80",
    socials: { instagram: "https://instagram.com/anuel" },
    description: "El lado mas agresivo del trap. Presencia dominante y energia imponente.",
  },
  {
    id: "brent-faiyaz",
    name: "BRENT FAIYAZ",
    role: "RNB LOUD",
    image: "https://images.unsplash.com/photo-1493225457124-a1a2a5fa36d1?auto=format&fit=crop&w=900&q=80",
    socials: { instagram: "https://instagram.com/brentfaiyaz" },
    description: "Voz hipnotica y atmosfera nocturna con textura R&B futurista.",
  },
  {
    id: "bad-bunny",
    name: "BAD BUNNY",
    role: "LATIN LOUD",
    image: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=900&q=80",
    socials: { instagram: "https://instagram.com/badbunnypr" },
    description: "Escala global, energia sin limites y shows visualmente devastadores.",
  },
];

export const events: Event[] = [
  {
    id: "kaskade-origin",
    title: "Kaskade: ORIGIN //",
    subtitle: "FACTORY TOWN",
    city: "Miami",
    dateLabel: "vie, 18 sept",
    startsAt: "2026-09-18T22:00:00-05:00",
    poster: "/images/4go_dj_green_alien_hero_2k.png",
    lineup: ["Kaskade"],
    organizer: "Cubic",
    venue: "Factory Town",
    price: 10,
    description: "Kaskade live in Miami at Factory Town for a special ORIGIN set.",
  },
  {
    id: "fisher-miami",
    title: "FISHER",
    subtitle: "FACTORY TOWN MIAMI",
    city: "Miami",
    dateLabel: "sáb, 26 sept",
    startsAt: "2026-09-26T22:00:00-05:00",
    poster: "/images/trap_loud_trio_artists.png",
    lineup: ["FISHER"],
    organizer: "Cubic",
    venue: "Factory Town",
    price: 130.5,
    description: "High energy house music with FISHER live in Miami.",
  },
  {
    id: "armin-van-buuren",
    title: "Armin van Buuren presents The Funk Tribu",
    subtitle: "NRG2000 TOUR",
    city: "Miami",
    dateLabel: "sáb, 10 oct",
    startsAt: "2026-10-10T22:00:00-05:00",
    poster: "/images/trap_loud_miami_mobile_2026.png",
    lineup: ["Armin van Buuren", "Funk Tribu"],
    organizer: "Cubic",
    venue: "Factory Town",
    price: 75.0,
    description: "Trance & high BPM energy with Armin van Buuren.",
  },
  {
    id: "strippers-fl-tour",
    title: "Strippers FL Tour 2026",
    subtitle: "FACTORY TOWN",
    city: "Miami",
    dateLabel: "mié, 15 sep",
    startsAt: "2026-09-15T21:00:00-05:00",
    poster: "/images/trap_loud_sanjuan_mobile_2026.png",
    lineup: ["Strippers"],
    organizer: "Cubic",
    venue: "Factory Town",
    price: 75.0,
    description: "Strippers FL Tour 2026 live at Factory Town.",
  },
  {
    id: "ahana-yoga",
    title: "Ahana x Perkhaus- Yoga activation w/live DJ",
    subtitle: "YOGA & MUSIC",
    city: "Miami",
    dateLabel: "mar, 25 ago",
    startsAt: "2026-08-25T18:00:00-05:00",
    poster: "/images/rnb_loud_la_mobile_2026.png",
    lineup: ["Cornelinho"],
    organizer: "Cubic",
    venue: "Ahana yoga",
    price: 0,
    description: "Yoga class with live DJ ambient set.",
  },
  {
    id: "satellite-33hr",
    title: "Satellite: 33+ Hour III Points Closing Party",
    subtitle: "CLUB SPACE",
    city: "Miami",
    dateLabel: "18 oct - 20 oct",
    startsAt: "2026-10-18T23:00:00-05:00",
    poster: "/images/rnb_loud_brent_1778966427864.png",
    lineup: ["Seth Troxler", "Marco Carola", "Honey Dijon"],
    organizer: "Cubic",
    venue: "Club Space Miami",
    price: 35.0,
    description: "33+ Hour non-stop closing marathon party at Club Space.",
  },
  {
    id: "unreal-miami",
    title: "UNREAL",
    subtitle: "INFINITY ROOM",
    city: "Miami",
    dateLabel: "vie, 13 nov",
    startsAt: "2026-11-13T23:00:00-05:00",
    poster: "/images/trap_loud_event_1779161392003.png",
    lineup: ["UNREAL Residents"],
    organizer: "Cubic",
    venue: "Factory Town",
    price: 49.99,
    description: "Unreal Techno experience in the Infinity Room at Factory Town.",
  },
  {
    id: "satellite-disco-lines",
    title: "Satellite: Disco Lines, Four Tet B2B Floating Points",
    subtitle: "CLUB SPACE B2B",
    city: "Miami",
    dateLabel: "sáb, 17 oct",
    startsAt: "2026-10-17T23:00:00-05:00",
    poster: "/images/latin_loud_medellin_mobile_2026.png",
    lineup: ["Disco Lines", "Four Tet", "Floating Points", "Daphni"],
    organizer: "Cubic",
    venue: "Club Space Miami",
    price: 45.0,
    description: "Exclusive B2B marathon set at Space Terrace.",
  },
  {
    id: "elderbrook-dj-set",
    title: "Elderbrook (DJ Set), Laurence Guy, & Collect 200",
    subtitle: "DOWNTOWN MIAMI",
    city: "Miami",
    dateLabel: "vie, 21 ago",
    startsAt: "2026-08-21T23:00:00-05:00",
    poster: "/images/roa_artist_1779161704881.png",
    lineup: ["Elderbrook", "Laurence Guy", "Collect 200"],
    organizer: "Cubic",
    venue: "Club Space Miami",
    price: 30.0,
    description: "Melodic & emotive electronic music live with Elderbrook.",
  },
  {
    id: "satellite-cloonee",
    title: "Satellite: Cloonee, Miluhska, Omar+ & Vintage Culture",
    subtitle: "SPACE TERRACE",
    city: "Miami",
    dateLabel: "jue, 15 oct",
    startsAt: "2026-10-15T23:00:00-05:00",
    poster: "/images/rauw_alejandro_card_bg.png",
    lineup: ["Cloonee", "Vintage Culture", "Miluhska"],
    organizer: "Cubic",
    venue: "Club Space Miami",
    price: 40.0,
    description: "Tech house vibes with Cloonee and Vintage Culture.",
  },
  {
    id: "dawg-night",
    title: "DAWG NIGHT",
    subtitle: "OMAR COURTZ EXPERIENCE",
    city: "Loja",
    dateLabel: "25 JUL 2026",
    startsAt: "2026-07-25T21:00:00-05:00",
    poster: "/images/omar_courtz_card_bg.jpg",
    lineup: ["OMAR COURTZ"],
    organizer: "Cubic",
    organizers: ["Cubic", "4Go"],
    venue: "Cubic Loja",
    description:
      "Voz única y flows de la calle. Autenticidad reggaetonera en Cubic Loja con producción de nivel mundial.",
  },
  {
    id: "nocturne-loud",
    title: "NOCTURNE LOUD",
    subtitle: "DRAKE / PND / CARTI",
    city: "Loja",
    dateLabel: "26 JUL 2026",
    startsAt: "2026-07-26T21:00:00-05:00",
    poster: "/images/now4go-hero-presentation-hd-v3.png",
    lineup: ["DRAKE", "PND", "PLAYBOI CARTI"],
    organizer: "Cubic",
    organizers: ["Cubic", "4Go"],
    venue: "Cubic Loja",
    description:
      "La fiesta exclusiva del fin de semana en Cubic Loja. Sonido e iluminación de alta fidelidad.",
  },
  {
    id: "trap-loud",
    title: "TRAP LOUD",
    subtitle: "YAN BLOCK EXPERIENCE",
    city: "Loja",
    dateLabel: "18 JUN 2026",
    startsAt: "2026-06-18T21:00:00-05:00",
    poster: "/images/trap_loud_trio_artists.png",
    lineup: ["DJ OFICIAL NENEZ"],
    organizer: "Cubic",
    venue: "Cubic Loja",
    description:
      "La escena subterranea cobra vida. Trap latino oscuro, bajo retumbante y energia inagotable. Luces rojas, beats pesados y acceso estricto.",
  },
  {
    id: "trap-loud-anuel",
    title: "TRAP LOUD",
    subtitle: "ANUEL EFFECT",
    city: "Loja",
    dateLabel: "15 AGO 2026",
    startsAt: "2026-08-15T22:00:00-05:00",
    poster: "/images/trap_loud_anuel_1778966415162.png",
    lineup: ["ANUEL AA", "y mas"],
    description:
      "El lado mas agresivo del trap. Una experiencia imponente, oscura y cinematica con el pionero del genero dictando el ritmo.",
  },
  {
    id: "rnb-loud",
    title: "RNB LOUD",
    subtitle: "NIGHT VISIONS",
    city: "Loja",
    dateLabel: "24 OCT 2026",
    startsAt: "2026-10-24T22:00:00-05:00",
    poster: "/images/rnb_loud_brent_1778966427864.png",
    lineup: ["BRENT FAIYAZ", "DRAKE", "y mas"],
    description:
      "Vibras lujosas y nocturnas. R&B sensual y futurista en una atmosfera envolvente donde el estilo y el sonido marcan la pauta.",
  },
  {
    id: "latin-loud",
    title: "LATIN LOUD",
    subtitle: "GLOBAL WAVE",
    city: "Loja",
    dateLabel: "10 DIC 2026",
    startsAt: "2026-12-10T20:00:00-05:00",
    poster: "/images/latin_loud_bad_bunny_1778966469259.png",
    lineup: ["BAD BUNNY", "RAUW ALEJANDRO", "y mas"],
    description:
      "Energia sin limites y orgullo latino. Una experiencia masiva, brillante y premium que redefine la fiesta underground a gran escala.",
  },
  {
    id: "tory-silver-purgatory",
    title: "Tory Silver, Annie Collette, and Julian Cubillos",
    subtitle: "LIVE AT PURGATORY",
    city: "New York",
    dateLabel: "jue, 17 sept",
    startsAt: "2026-09-17T20:00:00-05:00",
    poster: "/images/4go_red_girl_showcase.jpg",
    lineup: ["Tory Silver", "Annie Collette", "Julian Cubillos"],
    organizer: "Cubicolor",
    venue: "Purgatory",
    price: 25.0,
    description: "Live performance by Tory Silver, Annie Collette, and Julian Cubillos.",
  },
  {
    id: "lightroom-bowie",
    title: "Lightroom Live: Peter Gregson x Bowie",
    subtitle: "LIGHTROOM ARCHWAY",
    city: "Archway",
    dateLabel: "jue, 3 sept",
    startsAt: "2026-09-03T19:00:00-05:00",
    poster: "/images/now4go-hero-presentation-hd-v3.png",
    lineup: ["Peter Gregson", "Bowie"],
    organizer: "Cubic",
    venue: "Lightroom",
    price: 30.0,
    description: "Immersive sound experience with Peter Gregson x Bowie live.",
  },
  {
    id: "latin-loud-badbunny",
    title: "LATIN LOUD",
    subtitle: "BAD BUNNY & RAUW ALEJANDRO",
    city: "Quito",
    dateLabel: "10 DIC 2026",
    startsAt: "2026-12-10T20:00:00-05:00",
    poster: "/images/latin_loud_bad_bunny_1778966469259.png",
    lineup: ["BAD BUNNY", "RAUW ALEJANDRO"],
    description: "Energía sin límites y orgullo latino. Una experiencia masiva y brillante.",
  },
  {
    id: "rnb-loud-brent",
    title: "RNB LOUD",
    subtitle: "BRENT FAIYAZ NIGHT VISIONS",
    city: "Guayaquil",
    dateLabel: "11 NOV 2026",
    startsAt: "2026-11-05T21:30:00-05:00",
    poster: "/images/rnb_loud_brent_1778966427864.png",
    lineup: ["BRENT FAIYAZ"],
    description: "Vibras lujosas y nocturnas. R&B sensual y futurista en una atmósfera envolvente.",
  },
  {
    id: "urban-drop-roa",
    title: "URBAN DROP",
    subtitle: "ROA LIVE EXPERIENCE",
    city: "Cuenca",
    dateLabel: "18 SEP 2026",
    startsAt: "2026-09-18T22:00:00-05:00",
    poster: "/images/roa_artist_1779161704881.png",
    lineup: ["ROA"],
    description: "El futuro de la escena urbana. Versatilidad y melodías adictivas.",
  },
  {
    id: "trap-loud-sanjuan",
    title: "TRAP LOUD",
    subtitle: "SAN JUAN SPECIAL DROP",
    city: "Manta",
    dateLabel: "28 AGO 2026",
    startsAt: "2026-08-28T21:00:00-05:00",
    poster: "/images/trap_loud_event_1779161392003.png",
    lineup: ["DJ OFICIAL NENEZ"],
    description: "Edición especial frente al mar. Trap pesado, bajos retumbantes y energía de costa.",
  },
];

export const merch: MerchItem[] = [
  {
    id: "hoodie-redline",
    name: "Redline Hoodie",
    price: "$65",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "oversized-tee",
    name: "Oversized Heavy Tee",
    price: "$40",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "accessory-chain",
    name: "Underground Chain",
    price: "$30",
    image: "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "tactical-jacket",
    name: "Signal Tactical Jacket",
    price: "$95",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85",
  },
];

export function getEvents(): Event[] {
  return events;
}

